### ISSUE TITLE
Posible colaboración

### ISSUE THREAD

**Issue by cabustillo13** [Gustavovaler/e_Escuela#4]
¿Aceptas colaboradores o pull request de mejora para este proyecto?.

**Comment by Gustavovaler** [comment]
Hola como estas? Si claro, que tenes en mente? Este proyecto tenía la finalidad de ser una herramienta de ayuda pero me quede sin tiempo para continuar el desarrollo.

**Comment by cabustillo13** [comment]
Me gusta el propósito del proyecto. Voy a arrancar mejorando el README, y viendo la forma en qué planteaste el programa. Una vez hecho eso, y entendido bien cómo funciona tu código, aportar algo extra. Hazme colaborador y así ya empiezo con los pull request.

**Comment by Gustavovaler** [comment]
OK
